-- 创建 rate_limits 表用于用户使用限制追踪
CREATE TABLE IF NOT EXISTS rate_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL,
  identifier TEXT NOT NULL,
  usage_count INTEGER NOT NULL DEFAULT 1,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 创建唯一约束，确保每个标识符只有一条记录
CREATE UNIQUE INDEX IF NOT EXISTS idx_rate_limits_unique ON rate_limits(key, identifier);

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_rate_limits_key ON rate_limits(key);
CREATE INDEX IF NOT EXISTS idx_rate_limits_identifier ON rate_limits(identifier);

-- 启用行级安全策略 (RLS)
ALTER TABLE rate_limits ENABLE ROW LEVEL SECURITY;

-- 允许匿名用户插入记录
CREATE POLICY "Allow anonymous insert" ON rate_limits
  FOR INSERT
  WITH CHECK (true);

-- 允许匿名用户查询记录
CREATE POLICY "Allow anonymous select" ON rate_limits
  FOR SELECT
  USING (true);

-- 允许匿名用户更新记录
CREATE POLICY "Allow anonymous update" ON rate_limits
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

-- 创建清理旧数据的函数（可选：定期清理30天前的数据）
CREATE OR REPLACE FUNCTION cleanup_old_rate_limits()
RETURNS void AS $$
BEGIN
  DELETE FROM rate_limits
  WHERE created_at < NOW() - INTERVAL '30 days';
END;
$$ LANGUAGE plpgsql;

-- 添加注释
COMMENT ON TABLE rate_limits IS '用户使用限制追踪表';
COMMENT ON COLUMN rate_limits.key IS '使用限制键值，如 guest-analysis';
COMMENT ON COLUMN rate_limits.identifier IS '用户标识符，可以是token或ip hash';
COMMENT ON COLUMN rate_limits.usage_count IS '使用次数，默认为1，每次使用后累加';
COMMENT ON COLUMN rate_limits.timestamp IS '使用时间戳';
COMMENT ON COLUMN rate_limits.created_at IS '记录创建时间';
COMMENT ON COLUMN rate_limits.updated_at IS '记录更新时间';

-- 创建自动更新 updated_at 的触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 创建触发器
DROP TRIGGER IF EXISTS update_rate_limits_updated_at ON rate_limits;
CREATE TRIGGER update_rate_limits_updated_at
  BEFORE UPDATE ON rate_limits
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- 创建函数：安全地增加 usage_count
CREATE OR REPLACE FUNCTION increment_usage_count(
  p_key TEXT,
  p_identifier TEXT
)
RETURNS INTEGER AS $$
DECLARE
  v_new_count INTEGER;
BEGIN
  -- 尝试更新现有记录
  UPDATE rate_limits
  SET 
    usage_count = usage_count + 1,
    timestamp = NOW()
  WHERE key = p_key AND identifier = p_identifier
  RETURNING usage_count INTO v_new_count;

  -- 如果没有更新任何记录，则插入新记录
  IF NOT FOUND THEN
    INSERT INTO rate_limits (key, identifier, usage_count, timestamp)
    VALUES (p_key, p_identifier, 1, NOW())
    RETURNING usage_count INTO v_new_count;
  END IF;

  RETURN v_new_count;
END;
$$ LANGUAGE plpgsql;

-- 创建函数：获取当前 usage_count
CREATE OR REPLACE FUNCTION get_usage_count(
  p_key TEXT,
  p_identifier TEXT
)
RETURNS INTEGER AS $$
DECLARE
  v_count INTEGER;
BEGIN
  SELECT usage_count INTO v_count
  FROM rate_limits
  WHERE key = p_key AND identifier = p_identifier;

  RETURN COALESCE(v_count, 0);
END;
$$ LANGUAGE plpgsql;